export const RAW_LABELS: Record<string, string> = {
  Ortg: "Off Rating",
  usg: "Usage %",
  eFG: "eFG%",
  TS_per: "TS%",
  ORB_per: "Off Reb%",
  DRB_per: "Def Reb%",
  AST_per: "Assist%",
  TO_per: "Turnover%",
  blk_per: "Block%",
  stl_per: "Steal%",
  porpag: "PORPAG",
  adjoe: "Adj OE",
  drtg: "Def Rating",
  adrtg: "Adj DRtg",
  dporpag: "D-PORPAG",
  bpm: "BPM",
  ast_tov: "AST/TOV",
}

export const PERCENTILE_LABELS: Record<string, string> = {
  Ortg_percentile: "Off Rating",
  usg_percentile: "Usage",
  eFG_percentile: "eFG%",
  TS_per_percentile: "TS%",
  ORB_per_percentile: "Off Reb",
  DRB_per_percentile: "Def Reb",
  AST_per_percentile: "Assists",
  TO_per_percentile: "Turnover",
  blk_per_percentile: "Blocks",
  stl_per_percentile: "Steals",
  porpag_percentile: "PORPAG",
  adjoe_percentile: "Adj OE",
  drtg_percentile: "Def Rating",
  adrtg_percentile: "Adj DRtg",
  dporpag_percentile: "D-PORPAG",
}